# Generated by Django 3.2.9 on 2021-11-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211106_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_hero_name', models.CharField(max_length=255)),
                ('director_name', models.CharField(max_length=255)),
                ('cameraman_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Category Description')),
                ('movies_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
